apiVersion: apps/v1
kind: Deployment
metadata:
  name: excuse-generator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excuse-generator
  template:
    metadata:
      labels:
        app: excuse-generator
    spec:
      containers:
      - name: excuse-generator
        image: excuse_generator_api
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: excuse-generator-service
spec:
  type: NodePort
  selector:
    app: excuse-generator
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000