apiVersion: apps/v1
kind: Deployment
metadata:
  name: excuse-generator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: excuse-generator
  template:
    metadata:
      labels:
        app: excuse-generator
    spec:
      containers:
      - name: excuse-generator
        image: excuse_generator_api:1.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: excuse-secrets
              key: OPENAI_API_KEY
        - name: DEBUG_MODE
          value: "true"
        - name: ORIGINS
          value: "http://localhost:4200"
---
apiVersion: v1
kind: Service
metadata:
  name: excuse-generator-service
spec:
  type: NodePort
  selector:
    app: excuse-generator
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000